# Generated by Django 3.2.15 on 2023-10-25 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20231025_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Сумма заказа'),
        ),
    ]
