# Generated by Django 3.2.15 on 2023-10-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=128, verbose_name='Комментарии'),
        ),
    ]
