# Generated by Django 3.2.15 on 2023-10-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20231026_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличный'), ('cashless', 'Безналичный')], db_index=True, default='cashless', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
