# Generated by Django 3.2.15 on 2023-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличный', 'Наличный'), ('Безналичный', 'Безналичный')], db_index=True, default='Безналичный', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
